# Generated by Django 4.1.5 on 2023-01-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnstuff', '0002_book_author_book_is_bestselling_alter_book_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Bookstem',
        ),
    ]
