# Generated by Django 4.1.5 on 2023-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnstuff', '0005_book_stem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_stem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
