# Generated by Django 4.1.5 on 2023-01-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnstuff', '0007_author_alter_book_stem_slug_alter_book_stem_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Author address entries',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='learnstuff.address'),
        ),
    ]
